[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tip_vault = "J6uAbWr24AsXfhmW8cTannQ7ZE2cqqWiCLs9s9PqWMxz"

[programs.devnet]
tip_vault = "J6uAbWr24AsXfhmW8cTannQ7ZE2cqqWiCLs9s9PqWMxz"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test:localnet"
